// Generated by gencpp from file autocar/Values.msg
// DO NOT EDIT!


#ifndef AUTOCAR_MESSAGE_VALUES_H
#define AUTOCAR_MESSAGE_VALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autocar
{
template <class ContainerAllocator>
struct Values_
{
  typedef Values_<ContainerAllocator> Type;

  Values_()
    : throttle(0.0)
    , steering(0.0)  {
    }
  Values_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::autocar::Values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autocar::Values_<ContainerAllocator> const> ConstPtr;

}; // struct Values_

typedef ::autocar::Values_<std::allocator<void> > Values;

typedef boost::shared_ptr< ::autocar::Values > ValuesPtr;
typedef boost::shared_ptr< ::autocar::Values const> ValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autocar::Values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autocar::Values_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autocar::Values_<ContainerAllocator1> & lhs, const ::autocar::Values_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle &&
    lhs.steering == rhs.steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autocar::Values_<ContainerAllocator1> & lhs, const ::autocar::Values_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autocar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autocar::Values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autocar::Values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autocar::Values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autocar::Values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autocar::Values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autocar::Values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autocar::Values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39f463d271c2ca10c14182802c72c029";
  }

  static const char* value(const ::autocar::Values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39f463d271c2ca10ULL;
  static const uint64_t static_value2 = 0xc14182802c72c029ULL;
};

template<class ContainerAllocator>
struct DataType< ::autocar::Values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autocar/Values";
  }

  static const char* value(const ::autocar::Values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autocar::Values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 throttle\n"
"float64 steering\n"
;
  }

  static const char* value(const ::autocar::Values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autocar::Values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autocar::Values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autocar::Values_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOCAR_MESSAGE_VALUES_H
